// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadSettings(arg1:string):Promise<main.Config>;

export function SaveSettings(arg1:string,arg2:string):Promise<string>;
