// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchNews() {
  return window['go']['main']['App']['FetchNews']();
}

export function GetCachedNewsAge() {
  return window['go']['main']['App']['GetCachedNewsAge']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function SaveAPIKey(arg1) {
  return window['go']['main']['App']['SaveAPIKey'](arg1);
}

export function SaveSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2);
}
